Why was focusbear created?

Focusbear was created by Jeremy nagel and inspired by his own struggles as an individual that is diagnosed with ADHD and autism. More specifically, Jeremy experienced issues establishing healthy habits and was being adversely impacted by his addiction to his smartphone and computer. He realised he did not have the best coping mechanisms to manage the symptoms of his adhd, which ultimately led to him spending less time with his family due to poor productivity levels. He would often work after regular office hours in order to “catch up” on lost productivity. He would enter a hyper focus state that allowed him to get more work done during those few hours after work. However, he recognised that his patterns were not healthy,  nor were they in line with the values that Jeremy subscribed to as a person.

Since Jeremy had used various productivity tools and apps before, and had an epiphany. The underlying goal for most productivity apps and tools has been to allow users to become better organisers by allowing them to record vital information such as schedules, tasks, goals, ongoing commitments and meetings in an efficient manner. Due to this approach, the digital solutions that exist have mostly focused at creating visibility by externalising important information that a user is unable to hold at a mental level. Whilst these apps and tools  provide users with a non ambiguous way to see what task needs to be completed, which one(s) are higher in priority than others and what type of progress has been made been on each task, they fail to address the issues that are experienced by individuals that are neurodivergent. These individuals are susceptible to executive dysfunction, burnout, have a low frustration tolerance , emotional overwhelm and nervous system overload. This can lead to such individuals procrastinating on important tasks due to emotional overwhelm  and instead seeking hedonic value in the form of activities that provide instant gratification, such as scrolling instagram and YouTube reels. 

This is exactly why focus bear was created. The underlying assumption of focus bear is that users are operating in a “rigged” environment. In such an environment, modern digital products are pervasive, convenient, easy to access and provide users with a level of instant gratification, novelty and hedonic value that has never been provided at such a level in the history of human civilisation. The side effect of this phenomenon is that a person with adhd will invariably have their attention impaired and they will start to engage in task switching and/ or avoidance behaviours because their brain is constantly being primed by modern digital products. As a result, neurodivergent users find it more difficult to be productive. To further compound the issue, regular productivity tools and apps have the side effect of increasing the level of shame experienced by a person who is neurodivergent and trying to be productive, but still failing to accomplish their tasks and goals. 

Focus bear instead attempts to reduce access to modern digital products (‘social media, non productive websites and other forms of escapism online, such as news sites).  The app has been designed to prevent a user from engaging in forms of escapism online that hinder their productivity. For example, distracting websites  are blocked when a user is about to commence a focus session. The user is practically spared the trouble of constantly using their limited mental bandwidth fighting the temptation to engage in instant gratification behaviours by browsing distracting websites, apps or social media. Furthermore, users are guided through structured routines and the app helps them actively reduce the number of decisions that need to be made in the present moment. Focus bear essentially  recognises that a person who is neurodivergent will consume more energy to self regulate themselves and this in turn will impair their ability to be productive. 



What problem is focus bear solving?

Focus bear is attempting to solve the issues related to executive dysfunction that a neurodivergent individual might experience, particularly those with adhd. Focus bear recognises that there is a gap between a persons intention versus their ability to execute on something that they care about and intend on actioning. This  is particularly pronounced  in our contemporary world with an environment that is filled with myriad instant gratification options in the form of modern digital products (‘social media, distracting websites, video games etc). Neurodivergent People, such as those with adhd, are aware that they need to perform certain actions and engage in behaviours so that they can grow as individuals. However, the main issue experience in our modern society is their ability to initiate a particular task or behaviour,  be able to consistently sustain their attention while they engage in that task or behaviour, and be able to do this in manner that does not fully cognitively deplete their resources. 

The app achieves this by guiding them to engage in routines, it helps neurodivergent users minimise cognitive overwhelm and fatigue by providing them a structured way to execute their routines on a daily basis step by step. In this manner, the user does not have to rely entirely on their willpower and mental fortitude, which can work on a short term basis, but significantly drain a neurodivergent user on a long term basis.

Focus bear has been designed with neurodivergent challenges in mind. It’s unique features such as an A.i to detect whether a user is browsing content online that is relevant to their work, and if they can be redirected to a less distracted and low dopamine version of a specific online resource that they are browsing in the event a site is not on a block list within the app. This is essential for neurodivergent individual since their brains are primed to prioritise novelty, hedonic value and instant gratification.

The issue of time blindness is also another area that the app attempts to solve with the “late no more” feature. This is because people with adhd have poor internal gauges that allow them to determine how much time exactly should be spent on a particular task. They are very prone to underestimating how much time a task might take and constantly put off a task until a sense of urgency arises for them to start engaging with the task.

focus bear is also quite different from other productivity tools and apps since it recognises and is highly aware of how a neurodivergent user starts off with the intent to work on something, then they are met with internal cognitive overwhelm/avoidance/ and or/ anxiety, which then leads them to self soothe via high dominergic instant gratification Behaviours such as browsing YouTube and TikTok reel, end up losing focus and attentional resources , which then makes it harder for them to return to a baseline state where they cam adequately focus and complete their tasks. Focus bear understands that this is not an issue of laziness or low motivation. The app aims to create friction for a user when they begin behaving in a manner that is impulsive, without draining their cognitive resources by automating the environmental control aspect. 


Why do you think this mission is important?

I personally feel that focus bear’s mission is extremely important due to the increasing recognition of neurodivergent issues in  modern society. The current societal landscape and social discourses are becoming increasingly fragmented, more focused on hedonic value, instant gratification and technology is making it harder for people to focus in their daily lives. The distress tolerance, resilience, attentional capacity and ability to self regulate are all being significantly impaired by modern technology and digital products. Individual’s now spend a large amount of time on their phones and this has an adverse impact on their ability to self regulate, focus, and tolerate distress. This is particularly more pronounced for individuals with adhd.

The fundamental problem is that modern digital products (‘social media, gaming, distracting website and apps) are becoming increasingly more sophisticated at ensuring that their users continue to engage with them, regardless of the adverse impact in other areas of their lives. 

All of this created a modern environment that is essentially “rigged” for neurodivergent people. Societal discourses are known to perpetuate assumptions about neurodivergent people being prone to “Low motivation”, having “no ambition”, and being inherently undisciplined. With the modern environment, the task becomes even harder for a person with adhd to be productive when they can easily access content that provides them with instant gratification, novelty and hedonic value at a level that has previously never been seen in human history. This can exacerbate executive dysfunction significantly for neurodivergent individuals, and push them to a state where they are constantly pushing harder to disprove the negative assumptions that are perpetuated about them at a societal level via discourses. This inevitably leads to fatigue, frustration and burnout. An app like focus bear not only recognises the issues faced by people that are neurodivergent, but also provides the adequate behavioural scaffolding that is needed for them to flourish in modern society. This is extremely important because it can positively impact the life of a neurodivergent individual. The focus bear app allows neurodivergent individuals to live upto their full potential without shaming them for their issues with executive dysfunction or trivialising those issues.



How does focus bear’s work align with your personal values or interests?

As an individual that has always held an interest in psychology, human behaviour, technology, and sociology.  The work and mission of focus bear resonate with me personally on many levels. 

I am guided by my personal values of contribution, social impact, autonomy, mastery, competence, growth and resilience. Focus bear’s work aligns with me personally because I have always desired to make a strong positive social impact via leveraging my understanding of sociological theory, psychology, human computer interaction, user experience design, and technology to create digital products and experiences that will improve the lives of people using those products. I have also have a special interest in the area of healthtech, particularly digital products (apps) that are geared towards improving the mental health and overall resilience levels of other people. This aforementioned area is one that will experience significant growth due to high levels of consumer demand. I sincerely feel that my skills will allow me to positively impact the lives of people in this particular area as I embark on my product design career. I also feel like the work focus bear does genuinely resonate with me on a deep level. This is primarily because I have a good understanding of the specific challenges that are experienced by neurodivergent people .

I am acutely aware that not all behavioural struggles are the result of a lack personal responsibility, low levels of motivation and willpower, a lack of desire to work hard and having poor discipline. I understand that simply “working harder” is not always suitable and can lead to issues with burnout for individuals that are neurodivergent, particularly individuals with ADHD. I also feel like I can contribute to focus bear positively due to my unique skill set and passion for the problem being solved.  For example, focus bear aims to restrict users prior to them becoming engaged in escapist behaviours aimed at providing instant gratification. The app guides users through daily morning and evening routines in step by step sequence. This makes it easier for users to break through their inertia that paralyses them from taking action due to executive dysfunction. Focus bear also helps users modify their behaviours to be productive  in manner that is sustainable for them long term. There is a considerable amount of intersectionality between UX, psychology, systems thinking, technology and even sociological theory to an extent. I find this extremely fascinating and I feel my understanding in these areas is only going to further benefit the mission of focus bear. 



Do you personally relate to any of the challenges that focus bear aims to solve?

As a neurodivergent individual who has a formal ADHD diagnosis, I am able to relate to many of the challenges that focus aims to address.

Prior to my ADHD diagnosis, I experienced issues with executive dysfunction throughout my entire life. I realised in my teenage years that I was prone to “mental exhaustion” when I undertook too many “intensive tasks” at school In a row. I also found myself struggling to initiate any task that would require complex mental effort. However, I found that once I initiated the task, I would be able to focus easily and this was particularly the case in subjects I enjoyed, such as science and history. 

I also struggled with establish consistent sleep schedules prior to my ADHD diagnosis and would be sleep deprived due to pending work that i avoided doing during the day due to executive dysfunction. I had a poor understanding of ADHD prior to my diagnosis and lacked the terminology to properly articulate the problems I experienced. I also found it almost impossible to get any school work done at home without my friends studying with me in person or during an online session. Furthermore, becoming distracted and engaging in escapism is something that has improved with my understanding of adhd and after I received my diagnosis. I have also tried using the “self control” app in the past. However, I found that I could still drift away easily by accessing Wikipedia and other informational websites that were classified as “educational content” by the app. The constant push and pull would often exhaust me mentally when I was manually trying to stay away from distracting sites. In recent years, I find myself reverting back to some of these behaviours during periods of high stress or when I expect myself to perform at a high level. I have often relied on writing a manual checklist of tasks to perform upon waking up because I would wake up and immediately begin to drift by scrolling on my phone. This behaviour was particularly pronounced during the pandemic. Since then I have kept a list of actions that need to be crossed off in step by step sequence after waking up. This was particularly helpful for assessments as I attended university. I would break down assessments in key steps and cross each step off for a particular day. I would keep the paper as evidence of a “productive day” in order to create momentum. However, without meaningful distraction blockers or during times of high stress, I would simply ignore creating this checklist as the entire process was manual.
I certainly relate a lot to cognitive bandwidth becoming depleted as I am overloaded with more tasks. This phenomenon is particularly more pronounced. towards the end of the week. I have found that when I am not productive due to the issues I experience as a result of ADHD, it can negative,y impact my self image and confidence. 
 
From a product design perspective and from a personal point of view, I find being able to work for focus bear is something that is extremely meaningful to me as a person. It motivates me to unlock my true potential knowing that I have the right tools at my disposal.










